name: PWarp
version: '1.0-SNAPSHOT'
main: xyz.aeolia.pwarp.PWarp
api-version: '1.21'
depend:
  - "AeoliaLib"

commands:
  pwarp:
    permission: pwarp.pwarp
    usage: /<command> <player name/list/create/delete> <warp name/list>

permissions:
  pwarp.pwarp:
    default: true
  pwarp.max.1:
    default: true
  pwarp.admin:
    default: op